#!/bin/bash

export QT_QPA_PLATFORMTHEME=qt6ct
export QT_QPA_PLATFORM=wayland
export XDG_CURRENT_DESKTOP=labwc
export XDG_SESSION_TYPE=wayland
export XKB_DEFAULT_LAYOUT=es
export GDK_BACKEND=wayland

#/usr/lib/polkit-kde-authentication-agent-1 &
udiskie --tray --automount --notify &
pipewire &
noctalia
